GOOGLE_CLIENT_ID = "752773240253-tsuoqnm0j3ei4r57vjr8pusbk1rv7opt.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://gsc-data-extraction.streamlit.app/"
