GOOGLE_CLIENT_ID = "122318799297-ithfjhkbi4bcbk98gj3m4ehocmknqm4u.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
REDIRECT_URI = "https://gsc-data-extraction.streamlit.app/ "
